# Generated by Django 4.1.5 on 2025-06-03 13:30

from django.db import migrations, models
import django.db.models.deletion

def load_initial_data(apps, schema_editor):
    Fator = apps.get_model('amostras', 'Fator')
    Unidade = apps.get_model('amostras', 'Unidade')

    # Criando fatores
    fator_padrao = Fator.objects.create(simbolo='', fator=1.0)
    fator_u = Fator.objects.create(simbolo='u', fator=0.000001)
    fator_m = Fator.objects.create(simbolo='m', fator=0.001)
    fator_K = Fator.objects.create(simbolo='K', fator=1000)
    fator_M = Fator.objects.create(simbolo='M', fator=1000000)

    # Criando unidades
    Unidade.objects.create(unidade='grama', simbolo='g', fator_multiplicador=fator_padrao)
    Unidade.objects.create(unidade='litro', simbolo='L', fator_multiplicador=fator_padrao)
    Unidade.objects.create(unidade='metro Cubico', simbolo='m3', fator_multiplicador=fator_padrao)
    

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=5, unique=True)),
                ('fator', models.FloatField(default=1.0, verbose_name='Fator de conversão')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=20, unique=True)),
                ('simbolo', models.CharField(max_length=5, unique=True)),
                ('fator_multiplicador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amostras.fator', verbose_name='Multiplicador')),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome da amostra')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateTimeField(verbose_name='Data de Recebimento')),
                ('especificacao_material', models.TextField(verbose_name='Especificação')),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Quantidade')),
                ('data_cadastro', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de atualização')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amostras.unidade', verbose_name='Unidade de medida')),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
