# Generated by Django 4.1.5 on 2025-06-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='fator_multiplicador',
        ),
        migrations.AddField(
            model_name='amostra',
            name='fator_multiplicador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='amostras.fator', verbose_name='Multiplicador'),
            preserve_default=False,
        ),
    ]
