# Generated by Django 4.1.5 on 2025-06-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0012_autorizacao_equipamento_and_more'),
        ('amostras', '0002_remove_unidade_fator_multiplicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.local_instalacao', verbose_name='Localização'),
        ),
    ]
