# Generated by Django 4.1.5 on 2023-01-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0006_rename_tipos_tipo_remove_usuario_nomefamilia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_fabricante", models.CharField(max_length=80)),
                (
                    "endereco_fabricante",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                (
                    "nome_contato_fabricante",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "telefone_contato",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "email_contato_fabricante",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "site_Fabricante",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("dados_adicionais", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Local_instalacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predio", models.CharField(max_length=10)),
                ("piso", models.CharField(max_length=10)),
                ("sala", models.CharField(max_length=10)),
                ("armario", models.CharField(max_length=10)),
                ("prateleira", models.CharField(max_length=10)),
                ("apelido_local", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo_equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_tipo", models.CharField(max_length=50)),
                ("descricao_tipo", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material_consumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_material", models.CharField(max_length=50)),
                ("especificacao_material", models.TextField(blank=True, null=True)),
                ("unidade_material", models.CharField(max_length=10)),
                ("simbolo_unidade_material", models.CharField(max_length=5)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.fabricante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_equipamento", models.CharField(max_length=80)),
                ("modelo", models.CharField(max_length=80)),
                ("data_compra", models.DateTimeField(auto_now=True, null=True)),
                (
                    "data_ultima_calibracao",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                ("data_cadastro", models.DateTimeField(auto_now=True)),
                ("patrimonio", models.CharField(max_length=30)),
                (
                    "fabricante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.fabricante",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.local_instalacao",
                    ),
                ),
                (
                    "tipo_equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.tipo_equipamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
