# Generated by Django 4.1.5 on 2023-02-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='potencia_eletrica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
