# Generated by Django 4.1.5 on 2023-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_media_nome_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_instalacao',
            name='apelido_local',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='armario',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='prateleira',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='sala',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
