# Generated by Django 4.1.5 on 2023-02-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_potencia_eletrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_instalacao',
            name='laboratorio',
            field=models.CharField(default='LpM', max_length=30),
            preserve_default=False,
        ),
    ]
