# Generated by Django 4.1.5 on 2023-01-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_local_instalacao_apelido_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.fabricante'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.local_instalacao'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
