# Generated by Django 4.1.5 on 2023-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_local_instalacao_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_instalacao',
            name='armario',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='piso',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='prateleira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='predio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='sala',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
