# Generated by Django 4.1.5 on 2023-02-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_alter_local_instalacao_armario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
