# Generated by Django 4.1.5 on 2023-01-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('equipamentos', '0004_alter_equipamento_fabricante_alter_equipamento_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='material_consumo',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.fabricante'),
        ),
    ]
