# Generated by Django 4.1.5 on 2023-01-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_alter_equipamento_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='material_consumo',
            field=models.ManyToManyField(blank=True, null=True, to='equipamentos.material_consumo'),
        ),
        migrations.AddField(
            model_name='media',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
