# Generated by Django 4.1.5 on 2023-02-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_remove_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='documentos',
            field=models.FileField(upload_to='files/'),
        ),
    ]
