# Generated by Django 4.1.5 on 2023-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_equipamento_material_consumo_media_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='armario',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='piso',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='prateleira',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='predio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='sala',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='material_consumo',
            name='nome_material',
            field=models.CharField(max_length=70),
        ),
    ]
