# Generated by Django 4.1.5 on 2023-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_equipamento_codigo_alter_local_instalacao_armario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['nome_equipamento']},
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ['nome_fabricante']},
        ),
        migrations.AlterModelOptions(
            name='local_instalacao',
            options={'ordering': ['-predio', 'piso', '-sala', '-armario', 'prateleira']},
        ),
        migrations.AlterModelOptions(
            name='material_consumo',
            options={'ordering': ['nome_material']},
        ),
        migrations.AlterModelOptions(
            name='tipo_equipamento',
            options={'ordering': ['nome_tipo']},
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='material_consumo',
            field=models.ManyToManyField(blank=True, to='equipamentos.material_consumo'),
        ),
    ]
