# Generated by Django 4.1.5 on 2023-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_media_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
