# Generated by Django 4.1.5 on 2023-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_alter_equipamento_options_alter_fabricante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_ultima_calibracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
