# Generated by Django 4.1.5 on 2023-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_alter_equipamento_data_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_equipamento',
            name='sigla',
            field=models.CharField(default='tes', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
