# Generated by Django 4.1.5 on 2023-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0010_alter_local_instalacao_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='local_instalacao',
            name='apelido_local',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='media',
            name='documentos',
            field=models.FileField(max_length=255, upload_to='files/'),
        ),
    ]
