# Generated by Django 4.1.5 on 2023-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0010_tipo_equipamento_sigla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local_instalacao',
            options={'ordering': ['predio', 'piso', '-sala', '-armario', 'prateleira']},
        ),
    ]
