# Generated by Django 4.1.5 on 2025-05-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_ativo'),
        ('equipamentos', '0011_alter_equipamento_data_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao_equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.equipamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'equipamento')},
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='usuarios_treinados',
            field=models.ManyToManyField(related_name='equipamentos_treinados', through='equipamentos.Autorizacao_equipamento', to='usuarios.usuario'),
        ),
    ]
