# Generated by Django 4.1.5 on 2025-11-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0012_autorizacao_equipamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
