# Generated by Django 4.1.5 on 2023-02-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacao', models.CharField(choices=[('eq', 'Equipamento'), ('te', 'Tipo Equipamento'), ('fn', 'Fornecedor'), ('li', 'Local Instalação'), ('mc', 'Material Consumo'), ('me', 'media'), ('dc', 'Disciplina de Manutenção'), ('mf', 'Modo de Falha'), ('me', 'Modo de falha Equipamento'), ('nm', 'Nota Material'), ('ne', 'Nota Equipamento'), ('us', 'usuario'), ('tu', 'Tipo de Usuario'), ('rt', 'Relatório')], max_length=10)),
                ('movimento', models.CharField(choices=[('cd', 'Cadastro'), ('lt', 'Listagem'), ('ed', 'Edição'), ('dl', 'Delete'), ('lo', 'logon')], max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('alteracao', models.CharField(max_length=100)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.equipamento')),
            ],
            options={
                'ordering': ['-data_cadastro', 'usuario', 'nota_equipamento', 'transacao', 'movimento'],
            },
        ),
    ]
