# Generated by Django 4.1.5 on 2023-01-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notas", "0001_initial"),
        ("usuarios", "0006_rename_tipos_tipo_remove_usuario_nomefamilia_and_more"),
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transacao", models.CharField(max_length=30)),
                ("data_cadastro", models.DateTimeField(auto_now=True)),
                ("alteracao", models.CharField(max_length=30)),
                (
                    "Nota_equipamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="notas.nota_equipamento",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.equipamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
