# Generated by Django 4.1.5 on 2023-02-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('notas', '0001_initial'),
        ('usuarios', '0002_usuario_primeiro_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='nota_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notas.nota_equipamento'),
        ),
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
    ]
