# Generated by Django 4.1.5 on 2023-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='alteracao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='movimento',
            field=models.CharField(choices=[('cd', 'Cadastro'), ('lt', 'Listagem'), ('ed', 'Edição'), ('dl', 'Delete'), ('lo', 'logOn'), ('lf', 'logOff')], max_length=10),
        ),
    ]
