# Generated by Django 4.1.5 on 2023-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_log_alteracao_alter_log_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='transacao',
            field=models.CharField(choices=[('eq', 'Equipamento'), ('te', 'Tipo Equipamento'), ('fn', 'Fornecedor'), ('li', 'Local Instalação'), ('mc', 'Material Consumo'), ('me', 'media'), ('dc', 'Disciplina de Manutenção'), ('mf', 'Modo de Falha'), ('mq', 'Modo de falha Equipamento'), ('nm', 'Nota Material'), ('ne', 'Nota Equipamento'), ('us', 'usuario'), ('tu', 'Tipo de Usuario'), ('rt', 'Relatório')], max_length=10),
        ),
    ]
