# Generated by Django 4.1.5 on 2023-02-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_log_nota_equipamento_alter_log_equipamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['data_cadastro', 'usuario', 'nota_equipamento', 'transacao', 'movimento']},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='Nota_equipamento',
            new_name='nota_equipamento',
        ),
    ]
