# Generated by Django 4.1.5 on 2023-01-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0006_rename_tipos_tipo_remove_usuario_nomefamilia_and_more"),
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disciplina", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Modo_Falha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modo_falha", models.CharField(max_length=50)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="notas.disciplina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modo_falha_equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.equipamento",
                    ),
                ),
                (
                    "modo_falha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="notas.modo_falha",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota_material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantidade", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "Material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.material_consumo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota_equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_cadastro", models.DateTimeField(auto_now=True)),
                ("data_ocorrencia", models.DateField()),
                ("falha", models.BooleanField()),
                ("calibracao", models.BooleanField()),
                ("lubrificao", models.BooleanField()),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipamentos.equipamento",
                    ),
                ),
                (
                    "material",
                    models.ManyToManyField(
                        blank=True, null=True, to="notas.nota_material"
                    ),
                ),
                (
                    "modo_Falha_equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="notas.modo_falha_equipamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
