# Generated by Django 4.1.5 on 2023-02-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_equipamento_ativo'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modo_falha_equipamento',
            unique_together={('modo_falha', 'equipamento')},
        ),
    ]
