# Generated by Django 4.1.5 on 2023-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_equipamento',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, to='notas.nota_material'),
        ),
    ]
