# Generated by Django 4.1.5 on 2023-01-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_media'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_equipamento',
            name='material',
            field=models.ManyToManyField(to='notas.nota_material'),
        ),
        migrations.RemoveField(
            model_name='nota_material',
            name='Material',
        ),
        migrations.AddField(
            model_name='nota_material',
            name='Material',
            field=models.ManyToManyField(to='equipamentos.material_consumo'),
        ),
    ]
