# Generated by Django 4.1.5 on 2023-01-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('notas', '0002_alter_nota_equipamento_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_equipamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
