# Generated by Django 4.1.5 on 2023-03-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_modo_falha_equipamento_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modo_falha',
            options={'ordering': ['disciplina']},
        ),
        migrations.AlterModelOptions(
            name='modo_falha_equipamento',
            options={'ordering': ['equipamento', 'modo_falha']},
        ),
        migrations.AlterModelOptions(
            name='nota_equipamento',
            options={'ordering': ['data_ocorrencia', 'data_cadastro', 'equipamento']},
        ),
    ]
