# Generated by Django 4.1.5 on 2023-09-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_modo_falha_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota_equipamento',
            name='material',
        ),
        migrations.DeleteModel(
            name='Nota_material',
        ),
    ]
