# Generated by Django 4.1.5 on 2023-01-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_equipamento_material_consumo_media_documentos_and_more'),
        ('notas', '0003_alter_nota_equipamento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota_material',
            name='material',
        ),
        migrations.AddField(
            model_name='nota_material',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.material_consumo'),
            preserve_default=False,
        ),
    ]
