# Generated by Django 4.1.5 on 2024-07-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_remove_nota_equipamento_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_equipamento',
            name='melhoria',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
