# Generated by Django 4.1.5 on 2023-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_remove_nota_material_material_nota_material_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_equipamento',
            name='material',
            field=models.ManyToManyField(blank=True, to='notas.nota_material'),
        ),
    ]
