# Generated by Django 4.1.5 on 2025-10-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_usuario_ativo'),
        ('equipamentos', '0012_autorizacao_equipamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('data_recebimento', models.DateField()),
                ('data_fim', models.DateField()),
                ('prazo_dias', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.local_instalacao')),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('Responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portifolio.cor')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('massa', models.FloatField()),
                ('codigo_humano', models.CharField(max_length=255)),
                ('codigo_numerico', models.CharField(max_length=255, unique=True)),
                ('observacao', models.TextField(blank=True)),
                ('amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.amostra')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portifolio.cor')),
                ('locals_instalacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.local_instalacao')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portifolio.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='amostra',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.projeto'),
        ),
    ]
