# Generated by Django 4.1.5 on 2025-10-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='tonalidade',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
