# Generated by Django 4.1.5 on 2025-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_cor_tonalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='local',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='projeto',
        ),
        migrations.AlterField(
            model_name='amostra',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
