# Generated by Django 4.1.5 on 2025-10-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_remove_amostra_local_remove_etiqueta_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='massa',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
