# Generated by Django 4.1.5 on 2025-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_alter_etiqueta_massa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='tonalidade',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='codigo_humano',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
