# Generated by Django 4.1.5 on 2025-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_alter_cor_tonalidade_alter_etiqueta_codigo_humano_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='locals_instalacao',
            new_name='local_instalacao',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='Responsavel',
            new_name='responsavel',
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='massa',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
