# Generated by Django 4.1.5 on 2025-10-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0012_autorizacao_equipamento_and_more'),
        ('portifolio', '0006_rename_locals_instalacao_etiqueta_local_instalacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='local_instalacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.local_instalacao'),
        ),
    ]
