# Generated by Django 4.1.5 on 2025-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_alter_etiqueta_local_instalacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Controle de sequência de etiquetas',
                'verbose_name_plural': 'Controle de sequência de etiquetas',
            },
        ),
    ]
