# Generated by Django 4.1.5 on 2023-02-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
