# Generated by Django 4.1 on 2023-01-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(default="vazio", max_length=10),
            preserve_default=False,
        ),
    ]
