# Generated by Django 4.1.5 on 2023-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_primeiro_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
