# Generated by Django 4.1 on 2023-01-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_tipos_alter_usuario_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.tipos"
            ),
        ),
    ]
