# Generated by Django 4.1 on 2023-01-17 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_usuario_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeFamilia", models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="nomeFamilia",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.familia",
            ),
            preserve_default=False,
        ),
    ]
