# Generated by Django 4.1.5 on 2025-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_ativo_alter_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primeiro_acesso',
            field=models.BooleanField(),
        ),
    ]
