# Generated by Django 4.1.5 on 2023-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_familia_usuario_nomefamilia"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tipos",
            new_name="Tipo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nomeFamilia",
        ),
        migrations.AddField(
            model_name="usuario",
            name="chapa",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Familia",
        ),
    ]
